import fs from 'node:fs/promises';
import {Workbook, SpreadsheetFile} from '@oai/artifact-tool';
import sharp from 'sharp';
const dir = new URL('.', import.meta.url).pathname;
const products = JSON.parse(await fs.readFile(dir+'produk.json','utf8'));
await fs.mkdir(dir+'foto',{recursive:true});
for (const [i,p] of products.entries()) {
  const res=await fetch(p.image_url,{signal:AbortSignal.timeout(30000)});
  if(!res.ok) throw new Error(`Foto ${p.name}: ${res.status}`);
  const bytes=Buffer.from(await res.arrayBuffer());
  const info=await sharp(bytes).metadata();
  if(!info.width || !info.height) throw new Error('Gambar tidak valid');
  p.file=`foto/${String(i+1).padStart(2,'0')}-${p.name.toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g,'-')}.${info.format==='jpeg'?'jpg':info.format}`;
  await fs.writeFile(dir+p.file,bytes);
  console.log(`${i+1}. ${info.width}x${info.height} ${p.file}`);
}
await fs.writeFile(dir+'produk.json',JSON.stringify(products,null,2));
const wb=Workbook.create();
const s=wb.worksheets.add('Produk');
const headers=['Nama produk','Harga minimum IDR','Harga maksimum IDR','Sumber Shopee','Foto utama','Tanggal akses'];
const rows=products.map(p=>[p.name,p.min,p.max,p.url,p.file,'2026-09-04']);
s.getRange('A1:F14').values=[headers,...rows];
s.getRange('A1:F14').format.font={name:'Arial',size:11};
s.getRange('A1:F1').format={fill:'#303C38',font:{bold:true,color:'#FFFFFF'},rowHeight:32,wrapText:true};
s.getRange('A2:F14').format.rowHeight=80;
s.getRange('A1:A14').format.columnWidth=58;
s.getRange('B1:C14').format.columnWidth=23;
s.getRange('D1:E14').format.columnWidth=58;
s.getRange('F1:F14').format.columnWidth=18;
s.getRange('A1:F14').format.wrapText=true;
s.getRange('B2:C14').setNumberFormat('"Rp "#,##0');
s.getRange('A16').values=[['Cakupan: 13 dari 24 produk. Satu foto utama per produk.']];
s.getRange('A17').values=[['Harga publik saat akses; dapat berbeda menurut variasi dan promo.']];
s.showGridLines=false;
s.freezePanes.freezeRows(1);
console.log((await wb.inspect({kind:'table',range:'Produk!A1:C14',tableMaxRows:14,tableMaxCols:3})).ndjson);
console.log((await wb.inspect({kind:'match',searchTerm:'#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A',options:{useRegex:true,maxResults:10}})).ndjson);
const preview=await wb.render({sheetName:'Produk',range:'A1:C14',scale:1,format:'png'});
await fs.writeFile(dir+'preview.png',new Uint8Array(await preview.arrayBuffer()));
await (await SpreadsheetFile.exportXlsx(wb)).save(dir+'produk.xlsx');
await fs.writeFile(dir+'produk.csv','\ufeff'+s.getRange('A1:F14').values.map(row=>row.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\r\n'));
const escape=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
await fs.writeFile(dir+'katalog.html','<!doctype html><meta charset="utf-8"><title>ZYRABELLÉ — Produk publik</title><style>body{font:16px Arial;max-width:1100px;margin:40px auto;padding:20px;background:#faf8f4;color:#27302b}main{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:24px}article{background:white;padding:16px}img{width:100%;aspect-ratio:1;object-fit:contain}h2{font-size:17px}a{color:inherit}</style><h1>ZYRABELLÉ</h1><p>13 dari 24 produk · Diakses 4 September 2026 · Satu foto utama per produk</p><p>Harga publik dapat berubah menurut variasi dan promo. Sebelas produk lainnya belum berhasil diverifikasi.</p><main>'+products.map(p=>`<article><img src="${escape(p.file)}"><h2>${escape(p.name)}</h2><p>Rp ${p.min.toLocaleString('id-ID')}${p.max!==p.min?' – Rp '+p.max.toLocaleString('id-ID'):''}</p><a href="${escape(p.url)}">Lihat di Shopee</a></article>`).join('')+'</main>');
